<?php
    $sifra = $e ? $e->sifra : ''; 
?>

<form method="post" 
action="<?=App::config('url')?>vozilo/promjena/<?=$e->sifra?>">
  <h4 class="text-center">Informacije o vozilima</h4>
  
  
  <label>Proizvođač vozila
    <input type="text" name="proizvodac" value="<?=($e instanceof stdClass) ? $e->proizvodac : ''?>" />
  </label>

  <label>Model vozila
    <input type="text" name="model" value="<?=($e instanceof stdClass) ? $e->model : ''?>" />
  </label>

  <label>Godište vozila
    <input type="number" name="godiste" value="<?=($e instanceof stdClass) ? $e->godiste : ''?>" />
  </label>

  <label for="mjenjac" name="mjenjac" value="<?=($e instanceof stdClass) ? $e->mjenjac : ''?>">Mjenjač:</label>
<select id="mjenjac" name="mjenjac">
  <option label="Automatski">Automatski</option>
  <option label="Mehanički">Mehanički</option>
</select>


  <label for="gorivo" name="gorivo" value="<?=($e instanceof stdClass) ? $e->gorivo : ''?>">Gorivo:</label>
<select id="gorivo" name="gorivo">
  <option label="Dizel">Dizel</option>
  <option label="Benzin">Benzin</option>
  <option label="Hibrid">Hibrid</option>
  <option label="Baterija">Baterija</option>
</select>

  <label>Opis vozila
    <input type="text" name="opis" value="<?=($e instanceof stdClass) ? $e->opis : ''?>" />
  </label>

  <input type="hidden" name="novi" value="<?=($e instanceof stdClass) ? 0 : 1 ?>" />


 <!-- <input type="file" id="inputImage" name="file" accept=".jpg,.jpeg,.png,.gif,.bmp,.tiff">  
  <a href="#" id="spremi">Spremi</a>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div> -->

  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>vozilo">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>


</form>