<a class="success button expanded" 
    href="<?=App::config('url')?>vozilo/novi">
        Dodaj novo vozilo
</a>

<table>
    <thead>
        <tr>
            <th>Proizvođač vozila</th>
            <th>Model vozila</th>
            <th>Godište vozila</th>
            <th>Mjenjač</th>
            <th>Gorivo</th>
            <th>Opis</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $e): ?>
            <tr>
                <td><?=$e->proizvodac?></td>
                <td><?=$e->model?></td>
                <td><?=$e->godiste?></td>
                <td><?=$e->mjenjac?></td>
                <td><?=$e->gorivo?></td>
                <td><?=$e->opis?></td>
                <td>
                    <a href="<?=App::config('url')?>vozilo/promjena/<?=$e->sifra?>">Promjena
                     </a>
                    &nbsp;&nbsp;
                    <a href="<?=App::config('url')?>vozilo/brisanje/<?=$e->sifra?>" 
                        onclick="return confirm('Sigurno želite obrisati odabrano vozilo <?= $e->proizvodac . ' ' . $e->model ?>?');">Brisanje</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>