<div class="grid-x grid-padding-x" style="margin-top: 10px;">
    <div class="large-10 cell">
        <form action="<?=App::config('url')?>vozilo/index" method="get">
            <input type="text" name="uvjet" 
            placeholder="Unesite proizvođača ili model vozila"
            value="" />
        </form>
    </div>
    <div class="large-2 cell">
        <a href="<?=App::config('url')?>vozilo/novi"
            class="success button expanded">Dodaj novo vozilo</a>
    </div>
</div>



<table>
    <thead>
        <tr>
            <th>Proizvođač i model vozila</th>
            <th>Godište vozila</th>
            <th>Mjenjač</th>
            <th>Gorivo</th>
            <th>Opis</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $e): ?>
            <tr>
                <td><?=$e->proizvodac?> <?=$e->model?></td>
                <td><?=$e->godiste?></td>
                <td><?=$e->mjenjac?></td>
                <td><?=$e->gorivo?></td>
                <td><?=$e->opis?></td>
                <td>
                    <a href="<?=App::config('url')?>vozilo/promjena/<?=$e->sifra?>">Promjena
                     </a>
                    &nbsp;&nbsp;
                    <a href="<?=App::config('url')?>vozilo/brisanje/<?=$e->sifra?>" 
                        onclick="return confirm('Sigurno želite obrisati odabrano vozilo <?= $e->proizvodac . ' ' . $e->model ?>?');">Brisanje</a>
                </td>
            </tr>
        <?php endforeach; ?>

    </tbody>

</table>