<nav aria-label="Pagination">
  <ul class="pagination">
    <li class="pagination-previous">
        <a href="<?=App::config('url')?>vozilo/index?uvjet=<?=$uvjet?>&stranica=<?php echo $stranica-1;?>" 
        aria-label="Next page">Prethodna <span class="show-for-sr">stranica</span></a>
    </li>
    <li class="current"><span class="show-for-sr">Vi ste na stranici</span> 
        <?=$stranica?>/<?=$ukupnoStranica?>
    </li>
    <li class="pagination-next">
        <a href="<?=App::config('url')?>vozilo/index?uvjet=<?=$uvjet?>&stranica=<?php echo $stranica+1;?>" 
        aria-label="Next page">Sljedeća <span class="show-for-sr">stranica</span></a></li>
  </ul>
</nav>