<form method="post" 
action="<?=App::config('url')?>korisnik/novi">
  <h4 class="text-center">Dodavanje novog korisnika</h4>
  <label>Ime
    <input type="text" name="ime" value="<?=$korisnik->ime?>" />
  </label>

  <label>Prezime
    <input type="text" name="prezime" value="<?=$korisnik->prezime?>" />
  </label>

  <label>Email
    <input type="email" name="email" value="<?=$korisnik->email?>" />
  </label>

  <label>Broj mobitela
    <input type="number" name="broj_mobitela" value="<?=$korisnik->broj_mobitela?>" />
  </label>

  <label>Ime ulice
    <input type="text" name="ime_ulice" value="<?=$korisnik->ime_ulice?>" />
  </label>

  <label>Grad
    <input type="text" name="grad" value="<?=$korisnik->grad?>" />
  </label>

  <label>Država
    <input type="text" name="drzava" value="<?=$korisnik->drzava?>" />
  </label>

  <label>Broj vozačke
    <input type="text" name="broj_vozacke" value="<?=$korisnik->broj_vozacke?>" />
  </label>
  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>korisnik">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Dodaj"></input>
    </div>
  </div>
</form>