<form method="post" 
action="<?=App::config('url')?>korisnik/promjena/<?=$e->sifra?>">
  <h4 class="text-center">Informacije o korisnicima</h4>
  <label>Ime
    <input type="text" name="ime" value="<?=$e->ime?>" />
  </label>

  <label>Prezime
    <input type="text" name="prezime" value="<?=$e->prezime?>" />
  </label>

  <label>Email
    <input type="text" name="email" value="<?=$e->email?>" />
  </label>

  <label>Broj mobitela
    <input type="number" name="broj_mobitela" value="<?=$e->broj_mobitela?>" />
  </label>

  <label>Ime ulice
    <input type="text" name="ime_ulice" value="<?=$e->ime_ulice?>" />
  </label>

  <label>Grad
    <input type="text" name="grad" value="<?=$e->grad?>" />
  </label>

  <label>Država
  <?php require_once 'drzave.phtml'; ?>
</label>

  <label>Broj vozačke
    <input type="number" name="broj_vozacke" value="<?=$e->broj_vozacke?>" />
  </label>


 
  </label>
  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>korisnik">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Promjeni"></input>
    </div>
  </div>


</form>