<a href="<?=App::config('url')?>korisnik/novi"
    class="success button expanded">Dodaj novog korisnika</a>

<table>
    <thead>
        <tr>
            <th>Ime i prezime</th>
            <th>Email</th>
            <th>Broj mobitela</th>
            <th>Ime ulice</th>
            <th>Grad</th>
            <th>Država</th>
            <th>Broj vozačke</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($entiteti as $e): ?>
            <tr>
                <td><?=$e->ime?> <?=$e->prezime?></td>
                <td><?=$e->email?></td>
                <td><?=$e->broj_mobitela?></td>
                <td><?=$e->ime_ulice?></td>
                <td><?=$e->grad?></td>
                <td><?=$e->drzava?></td>
                <td><?=$e->broj_vozacke?></td>
                <td><a href="<?=App::config('url')?>korisnik/promjena/<?=$e->sifra?>">Promjena</a> 
                &nbsp;&nbsp;<a href="<?=App::config('url')?>korisnik/brisanje/<?=$e->sifra?>">Brisanje</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>