<form method="post" 
action="<?=App::config('url')?>lokacija/promjena/<?=$e->sifra?>">
  <h4 class="text-center">Informacije o poslovnicama</h4>
  
  
  <label>Naziv ulice
    <input type="text" name="naziv_ulice" value="<?=$e->naziv_ulice?>" />
  </label>

  <label>Broj ulice
    <input type="text" name="broj_ulice" value="<?=$e->broj_ulice?>" />
  </label>

  <label>Poštanski broj
    <input type="text" name="postanski_broj" value="<?=$e->postanski_broj?>" />
  </label>

  <label>Grad
    <input type="text" name="grad" value="<?=$e->grad?>" />
  </label>

  <label>Broj mobitela
    <input type="text" name="grad" value="<?=$e->grad?>" />
  </label>

  <label>Email
    <input type="email" name="email" value="<?=$e->email?>" />
  </label>

  <?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>lokacija">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>


</form>