<form action="<?=App::config('url')?>lokacija/promjena/<?=$e->sifra?>" 
method="post">

<label for="naziv">Naziv</label>
<input type="text" name="naziv" id="naziv" value="<?=$e->naziv_ulice?>">

<label for="lokacija">Lokacija</label>
<select name="lokacija" id="lokacija">
    <?php foreach($lokacije as $l): ?>
        <option
        <?php if ($e->lokacija==$l->sifra){
            echo ' selected="selected"';
        }
        ?>
        value="<?=$l->sifra?>"><?=$l->naziv_ulice?></option>
    <?php endforeach; ?>
</select>


<?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>lokacija">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>

</form>