<a class="success button expanded" 
    href="<?=App::config('url')?>lokacija/nova">
        Dodaj novu lokaciju/poslovnicu
</a>

<table>
    <thead>
        <tr>
            <th>Naziv i broj ulice</th>
            <th>Poštanski broj</th>
            <th>Grad</th>
            <th>Broj mobitela</th>
            <th>Email</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $e): ?>
            <tr>
                <td><?=$e->naziv_ulice?> <?=$e->broj_ulice?></td>
                <td><?=$e->postanski_broj?></td>
                <td><?=$e->grad?></td>
                <td><?=$e->broj_mobitela?></td>
                <td><?=$e->email?></td>
                <td>
                    <a href="<?=App::config('url')?>lokacija/promjena/<?=$e->sifra?>">Promjena
                     </a>
                    &nbsp;&nbsp;
                    <a href="<?=App::config('url')?>lokacija/brisanje/<?=$e->sifra?>" 
                        onclick="return confirm('Sigurno želite obrisati odabranu poslovnicu <?= $e->ime_ulice . ' ' . $e->broj_ulice ?>?');">Brisanje</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>