<?php
    $sifra = $e ? $e->sifra : ''; 
?>
<form method="post" action="<?=App::config('url')?>rezervacija/promjena/<?= $sifra?>">
  <h4 class="text-center">Detalji rezervacija</h4>

<label>Korisnik</label>
        <select name="korisnik" id="korisnik">
            <?php foreach($korisnici as $k): ?>
                <option
                <?php if($e instanceof stdClass && $e->korisnik == $k->sifra){
                    echo ' selected=="selected"';
                }
                ?>
                value="<?=$k->sifra?>"><?=$k->ime?> <?=$k->prezime?></option>
            <?php endforeach; ?>
        </select>

  <label>Poslovnica</label>
        <select name="lokacija" id="lokacija">
            <?php foreach($lokacije as $l): ?>
                <option
                <?php if($e instanceof stdClass && $e->lokacija == $l->sifra){
                    echo ' selected=="selected"';
                }
                ?>
                value="<?=$l->sifra?>"><?=$l->grad?> <?=$l->naziv_ulice?> <?=$l->broj_ulice?></option>
            <?php endforeach; ?>
        </select>

        <label>Vozilo</label>
        <select name="vozilo" id="vozilo">
            <?php foreach($vozila as $v): ?>
                <option
                <?php if($e instanceof stdClass && $e->vozilo == $v->sifra){
                    echo ' selected=="selected"';
                }
                ?>
                value="<?=$v->sifra?>"><?=$v->proizvodac?> <?=$v->model?></option>
            <?php endforeach; ?>
        </select>

  <label>Cijena
    <input type="text" name="cijena" value="<?=($e instanceof stdClass) ? $e->cijena : ''?>" />
  </label>

  <label>Datum preuzimanja
    <input type="date" name="datum_preuzimanja" value="<?=($e instanceof stdClass) ? $e->datum_preuzimanja : ''?>" />
  </label>

  <label>Datum povratka
    <input type="date" name="datum_povratka" value="<?=($e instanceof stdClass) ? $e->datum_povratka : ''?>" />
  </label>

  <input type="hidden" name="nova" value="<?=($e instanceof stdClass) ? 0 : 1 ?>" />
  
  <label>Osiguranje</label>
    <input type="checkbox" name="osiguranje" <?php 
    if($e instanceof stdClass && $e->osiguranje){
        echo 'checked="checked"';
    }

    ?>

  <?=$poruka?>

<div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>rezervacija">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
</div>

</form>