<form method="post" 
action="<?=App::config('url')?>rezervacija/promjena/<?=$e->sifra?>">
  <h4 class="text-center">Detalji rezervacija</h4>
  
<label>Korisnik</label>
        <select name="korisnik" id="korisnik">
            <?php foreach($korisnici as $k): ?>
                <option
                <?php if($e->korisnik == $k->sifra){
                    echo ' selected=="selected"';
                }
                ?>
                value="<?=$k->sifra?>"><?=$k->ime?> <?=$k->prezime?> <?=$k->broj_vozacke?></option>
            <?php endforeach; ?>
        </select>

  <label>Poslovnica</label>
        <select name="lokacija" id="lokacija">
            <?php foreach($lokacije as $l): ?>
                <option
                <?php if($e->lokacija == $l->sifra){
                    echo ' selected=="selected"';
                }
                ?>
                value="<?=$l->sifra?>"><?=$l->grad?> <?=$l->naziv_ulice?> <?=$l->broj_ulice?></option>
            <?php endforeach; ?>
        </select>

        <label>Vozilo</label>
        <select name="vozilo" id="vozilo">
            <?php foreach($vozila as $v): ?>
                <option
                <?php if($e->vozila == $v->sifra){
                    echo ' selected=="selected"';
                }
                ?>
                value="<?=$v->sifra?>"><?=$v->proizvodac?> <?=$v->model?></option>
            <?php endforeach; ?>
        </select>

  <label>Cijena
    <input type="text" name="cijena" value="<?=$e->cijena?>" />
  </label>

  <label>Datum preuzimanja
    <input type="text" name="datum_preuzimanja" value="<?=$e->datum_preuzimanja?>" />
  </label>

  <label>Datum povratka
    <input type="text" name="datum_povratka" value="<?=$e->datum_povratka?>" />
  </label>
  
  <label>Certificiran</label>
    <input type="checkbox" name="osiguranje" <?php 
    if($e->osiguranje){
        echo 'checked="checked"';
    }

    ?>

  <?=$poruka?>

<div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>narudzba">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
</div>

</form>